Repository plexe-ai/plexe, pull requests merged in 2025-04, with the labels that each got.

#84 chore: clean up planning logic and prompts
  pyproject.toml
  smolmodels/config.py
  smolmodels/internal/common/provider.py
  smolmodels/internal/models/generation/planning.py
  smolmodels/internal/models/generators.py
  smolmodels/internal/models/utils.py
  smolmodels/templates/prompts/planning/generate.jinja
  smolmodels/templates/prompts/planning/select_metric.jinja
  smolmodels/templates/prompts/planning/system_prompt.jinja
Labels: bug, chore

#85 feature: PLX-23 benchmarking with openai mle-bench
  .gitignore
  CLAUDE.md
  poetry.lock
  pyproject.toml
  tests/benchmark/README.md
  tests/benchmark/__init__.py
  tests/benchmark/mle-bench-config.yaml.jinja
  tests/benchmark/mle_bench.py
  tests/benchmark/mlebench/__init__.py
  tests/benchmark/mlebench/core/__init__.py
  tests/benchmark/mlebench/core/config.py
  tests/benchmark/mlebench/core/models.py
  tests/benchmark/mlebench/core/runner.py
  tests/benchmark/mlebench/core/validator.py
  tests/benchmark/mlebench/runners/__init__.py
  tests/benchmark/mlebench/runners/grader.py
  tests/benchmark/mlebench/runners/setup.py
  tests/benchmark/mlebench/runners/test_runner.py
  tests/benchmark/mlebench/utils/__init__.py
  tests/benchmark/mlebench/utils/command.py
  tests/benchmark/mlebench/utils/error.py
Labels: enhancement

#87 feat: add explicit per-run timeout + logging
  pyproject.toml
  smolmodels/config.py
  smolmodels/internal/models/execution/process_executor.py
  smolmodels/internal/models/generators.py
  smolmodels/models.py
Labels: bug

#88 docs: add 'backed by yc' logo to readme
  README.md
  resources/backed-by-yc.png
Labels: documentation

#91 feature: re-implement using multi-agent framework
  .gitignore
  CLAUDE.md
  README.md
  examples/run_with_mlflow.py
  examples/santander_customer_transactions.py
  examples/spaceship_titanic.py
  poetry.lock
  pyproject.toml
  resources/demo-thumbnail.png
  scripts/dumpcode.py
  smolmodels/config.py
  smolmodels/directives.py
  smolmodels/internal/agents.py
  smolmodels/internal/chat_agents.py
  smolmodels/internal/common/provider.py
  smolmodels/internal/common/registries/__init__.py
  smolmodels/internal/common/registries/objects.py
  smolmodels/internal/common/utils/agents.py
  smolmodels/internal/common/utils/dataset_storage.py
  smolmodels/internal/common/utils/prompt_utils.py
  smolmodels/internal/common/utils/pydantic_utils.py
  smolmodels/internal/models/callbacks/mlflow.py
  smolmodels/internal/models/entities/code.py
  smolmodels/internal/models/generation/training.py
  smolmodels/internal/models/generators.py
  smolmodels/internal/models/tools/code_generation.py
  smolmodels/internal/models/tools/datasets.py
  smolmodels/internal/models/tools/evaluation.py
  smolmodels/internal/models/tools/execution.py
  smolmodels/internal/models/tools/generation_tools.py
  smolmodels/internal/models/tools/metrics.py
  smolmodels/internal/models/tools/metrics_tools.py
  smolmodels/internal/models/tools/response_formatting.py
  smolmodels/internal/models/tools/search_tools.py
  smolmodels/internal/models/tools/validation.py
  smolmodels/internal/models/tools/validation_tools.py
  smolmodels/internal/models/utils.py
  smolmodels/internal/models/validation/composites/inference.py
  smolmodels/internal/models/validation/primitives/predict.py
  smolmodels/internal/schemas/resolver.py
  smolmodels/main.py
  smolmodels/models.py
  smolmodels/templates/prompts/agent/agent_manager_prompt.jinja
  smolmodels/templates/prompts/agent/chat-system-prompt.yaml
  smolmodels/templates/prompts/agent/manager_prompt_templates.yaml
  smolmodels/templates/prompts/agent/mle_prompt_templates.yaml
  smolmodels/templates/prompts/agent/mlops_prompt_templates.yaml
  smolmodels/templates/prompts/agent/mls_prompt_templates.yaml
  smolmodels/templates/prompts/schemas/base.jinja
  smolmodels/templates/prompts/schemas/generate_from_intent.jinja
  smolmodels/templates/prompts/schemas/identify_target.jinja
  smolmodels/templates/prompts/training/fix.jinja
  smolmodels/templates/prompts/training/generate.jinja
  smolmodels/templates/prompts/training/review.jinja
  tests/integration/test_model_description.py
  tests/integration/test_schema_validation.py
  tests/unit/test_callbacks.py
  tox.ini
Labels: documentation, enhancement, refactor

#98 docs: add plexe website to readme
  README.md
Labels: documentation

#90 feat: add support for ray to use distributed training
  README.md
  plexe/config.py
  plexe/internal/agents.py
  plexe/internal/models/execution/ray_executor.py
  plexe/internal/models/tools/execution.py
  plexe/models.py
  poetry.lock
  pyproject.toml
  tests/integration/test_ray_integration.py
  tests/unit/internal/models/execution/test_factory.py
  tests/unit/internal/models/execution/test_ray_executor.py
Labels: enhancement

#106 feature: "chain of thought" logging
  CLAUDE.md
  README.md
  docker/.env.example
  docker/.gitignore
  docker/README.md
  docker/__init__.py
  docker/api/Dockerfile
  docker/api/__init__.py
  docker/api/app.py
  docker/api/app/__init__.py
  docker/api/app/models/__init__.py
  docker/api/app/models/requests.py
  docker/api/app/models/responses.py
  docker/api/app/routes/__init__.py
  docker/api/app/routes/jobs.py
  docker/api/app/routes/models.py
  docker/api/app/routes/predictions.py
  docker/api/app/services/__init__.py
  docker/api/app/services/metadata.py
  docker/api/app/services/prediction.py
  docker/api/app/services/queue.py
  docker/api/app/utils/__init__.py
  docker/api/main.py
  docker/docker-compose.yml
  docker/poetry.lock
  docker/pyproject.toml
  docker/tests/scripts/model_build.py
  docker/tests/scripts/prediction.py
  docker/ui/Dockerfile
  docker/ui/app.py
  docker/worker/Dockerfile
  docker/worker/__init__.py
  docker/worker/main.py
  docker/worker/services/__init__.py
  docker/worker/services/metadata.py
  docker/worker/services/queue.py
  docker/worker/utils/__init__.py
  docs/architecture/multi-agent-system.md
  examples/santander_customer_transactions.py
  examples/spaceship_titanic.py
  plexe/callbacks.py
  plexe/config.py
  plexe/fileio.py
  plexe/internal/agents.py
  plexe/internal/chat_agents.py
  plexe/internal/common/utils/chain_of_thought/__init__.py
  plexe/internal/common/utils/chain_of_thought/adapters.py
  plexe/internal/common/utils/chain_of_thought/callable.py
  plexe/internal/common/utils/chain_of_thought/emitters.py
  plexe/internal/common/utils/chain_of_thought/protocol.py
  plexe/internal/models/callbacks/mlflow.py
  plexe/internal/models/tools/datasets.py
  plexe/internal/models/tools/execution.py
  plexe/main.py
  plexe/models.py
  plexe/templates/prompts/agent/chat-system-prompt.yaml
  plexe/templates/prompts/utils/cot_summarize.jinja
  plexe/templates/prompts/utils/system_prompt.jinja
  poetry.lock
  pyproject.toml
Labels: enhancement

#109 fix: make process executor clean up after itself
  plexe/internal/models/execution/process_executor.py
  plexe/internal/models/tools/execution.py
  pyproject.toml
Labels: bug, enhancement

#110 fix: improve process executor error handling
  plexe/internal/common/utils/response.py
  plexe/internal/models/execution/executor.py
  plexe/internal/models/execution/process_executor.py
  plexe/internal/models/tools/execution.py
  pyproject.toml
  tests/unit/internal/models/execution/test_process_executor.py
Labels: bug, enhancement
