Repository plexe-ai/plexe, pull requests merged in 2025-02, with the labels that each got.

#30 Fix/improve predictor generation prompts
  poetry.lock
  pyproject.toml
  smolmodels/config.py
  smolmodels/internal/models/generation/inference.py
  smolmodels/internal/models/generators.py
  smolmodels/models.py
Labels: bug, enhancement

#32 feature: add torch (cpu) to supported packages
  poetry.lock
  pyproject.toml
  smolmodels/config.py
Labels: enhancement

#35 fix: configure logging without modifying root logger
  smolmodels/config.py
  smolmodels/internal/data_generation/__init__.py
Labels: bug

#36 refactor: clean up model build
  poetry.lock
  pyproject.toml
  smolmodels/config.py
  smolmodels/internal/models/entities/node.py
  smolmodels/internal/models/entities/stopping_condition.py
  smolmodels/internal/models/generation/planning.py
  smolmodels/internal/models/generators.py
  smolmodels/internal/models/utils.py
  smolmodels/models.py
  tests/unit/test_data_generation.py
Labels: enhancement, refactor

#37 chore: add basic integration tests
  README.md
  tests/integration/test_model_integration.py
  tests/utils/utils.py
Labels: chore

#38 docs: update readme for clarity
  README.md
Labels: documentation

#40 docs: change readme toc to horizontal
  README.md
Labels: documentation

#41 docs: add early release warning to readme
  README.md
Labels: documentation

#42 fix: change early release banner to be more helpful
  README.md
Labels: documentation

#49 fix: update previously expired discord link
  README.md
Labels: bug

#56 refactor: move save_model and load_model to `fileio` module
  smolmodels/__init__.py
  smolmodels/fileio.py
  smolmodels/models.py
Labels: refactor

#59 feat: add support for fine-tuning pre-trained models
  poetry.lock
  pyproject.toml
  smolmodels/config.py
  smolmodels/internal/common/utils/response.py
  smolmodels/internal/datasets/core/generation/combined.py
  smolmodels/internal/models/execution/process_executor.py
  smolmodels/internal/models/generation/inference.py
  smolmodels/internal/models/generators.py
  smolmodels/internal/models/validation/composites/inference.py
  smolmodels/internal/models/validation/primitives/predict.py
  tests/integration/test_model_integration.py
  tests/utils/utils.py
Labels: enhancement

#64 feat: separate dataset generation from model building
  README.md
  pyproject.toml
  smolmodels/__init__.py
  smolmodels/config.py
  smolmodels/datasets.py
  smolmodels/fileio.py
  smolmodels/internal/common/datasets/adapter.py
  smolmodels/internal/common/utils/pydantic_utils.py
  smolmodels/internal/datasets/core/generation/base.py
  smolmodels/internal/datasets/core/generation/combined.py
  smolmodels/internal/datasets/core/generation/simple_llm.py
  smolmodels/internal/datasets/generator.py
  smolmodels/internal/models/execution/process_executor.py
  smolmodels/internal/models/generation/inference.py
  smolmodels/internal/models/generation/training.py
  smolmodels/internal/models/generators.py
  smolmodels/internal/models/validation/composites/inference.py
  smolmodels/internal/models/validation/primitives/predict.py
  smolmodels/internal/schemas/__init__.py
  smolmodels/internal/schemas/resolver.py
  smolmodels/models.py
  tests/integration/test_integration_heart_attack_prediction.py
  tests/integration/test_integration_sentiment_analysis.py
  tests/integration/test_model_integration.py
  tests/unit/internal/datasets/__init__.py
  tests/unit/internal/datasets/core/__init__.py
  tests/unit/internal/datasets/core/generation/__init__.py
  tests/unit/internal/datasets/core/generation/utils/__init__.py
  tests/unit/internal/datasets/core/generation/utils/test_oversampling.py
  tests/unit/internal/models/execution/test_process_executor.py
  tests/unit/test_data_generation.py
  tests/unit/test_datasets.py
Labels: bug, enhancement, refactor

#63 chore: divide inference code generation into individual stages
  pyproject.toml
  smolmodels/config.py
  smolmodels/internal/models/generation/inference.py
Labels: chore

#66 fix: add check for litellm response format support
  pyproject.toml
  smolmodels/internal/common/provider.py
  tests/unit/test_datasets.py
Labels: bug, chore

#65 feat: use pydantic for input/output/dataset schemas
  README.md
  pyproject.toml
  smolmodels/config.py
  smolmodels/datasets.py
  smolmodels/fileio.py
  smolmodels/internal/common/datasets/adapter.py
  smolmodels/internal/common/utils/pandas_utils.py
  smolmodels/internal/common/utils/pydantic_utils.py
  smolmodels/internal/datasets/core/generation/base.py
  smolmodels/internal/datasets/core/generation/combined.py
  smolmodels/internal/datasets/core/generation/simple_llm.py
  smolmodels/internal/datasets/generator.py
  smolmodels/internal/models/generation/inference.py
  smolmodels/internal/models/generation/schema.py
  smolmodels/internal/models/generation/training.py
  smolmodels/internal/models/generators.py
  smolmodels/internal/models/utils.py
  smolmodels/internal/models/validation/composites/inference.py
  smolmodels/internal/models/validation/primitives/predict.py
  smolmodels/internal/schemas/resolver.py
  smolmodels/models.py
  tests/integration/test_integration_heart_attack_prediction.py
  tests/integration/test_integration_sentiment_analysis.py
  tests/unit/internal/generation/test_schema.py
  tests/unit/test_datasets.py
Labels: enhancement, refactor
